Repository openforcefield/qca-dataset-submission, pull requests merged in 2025-04, with the labels that each got.

#449 TM Benchmark Optimizations
  README.md
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/CS-A_subset.json
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/README.md
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/charged_organic.json
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/cifs_misc/AN_Li_b_0m_a.cif
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/cifs_misc/Pd(IPr)Cl(CH2Cl)(Pp-MeOPh3).cif
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/cifs_misc/Pd(IPr)O2(Pm-tol3).cif
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/cifs_misc/complex5.cif
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/cifs_misc/complex6.cif
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/cifs_misc/complex7.cif
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/cifs_misc/compound1.cif
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/cifs_misc/compound2.cif
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/cifs_misc/ups3623kg_am34_0m.cif
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/dataset.pdf
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/environment.yml
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/environment_full.yml
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/generate-dataset.ipynb
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/mol2_misc/1578470.mol2
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/mol2_misc/1578471.mol2
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/mol2_misc/1578472.mol2
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/mol2_misc/1578473.mol2
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/mol2_misc/1578474.mol2
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/mol2_misc/1578475.mol2
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/mol2_misc/1969583.mol2
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/mol2_misc/2117901.mol2
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/mol2_misc/2117902.mol2
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/mol2_misc/2117903.mol2
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/scaffold.json.bz2
  submissions/2025-04-03-TM-Benchmark-Optimization-Dataset-Step-1-v0.0/scaffold.py
Labels: tracking, validation-off

#453 Add complete hessians dataset
  README.md
  submissions/2025-04-14-OpenFF-Optimization-Hessians-2019-07-to-2025-03-v4.0/README.md
  submissions/2025-04-14-OpenFF-Optimization-Hessians-2019-07-to-2025-03-v4.0/dataset.json.bz2
  submissions/2025-04-14-OpenFF-Optimization-Hessians-2019-07-to-2025-03-v4.0/dataset.pdf.tar.gz
  submissions/2025-04-14-OpenFF-Optimization-Hessians-2019-07-to-2025-03-v4.0/dataset.smi
  submissions/2025-04-14-OpenFF-Optimization-Hessians-2019-07-to-2025-03-v4.0/full-env.yaml
  submissions/2025-04-14-OpenFF-Optimization-Hessians-2019-07-to-2025-03-v4.0/generate-dataset.ipynb
  submissions/2025-04-14-OpenFF-Optimization-Hessians-2019-07-to-2025-03-v4.0/input-env.yaml
  submissions/2025-04-14-OpenFF-Optimization-Hessians-2019-07-to-2025-03-v4.0/optimizations.json.tar.gz
Labels: tracking, compute-pr453

#454 Add ChEMBL optimizations
  README.md
  submissions/2025-04-14-OpenFF-Additional-ChEMBL-Fragment-Optimizations-v4.0/README.md
  submissions/2025-04-14-OpenFF-Additional-ChEMBL-Fragment-Optimizations-v4.0/dataset.json.bz2
  submissions/2025-04-14-OpenFF-Additional-ChEMBL-Fragment-Optimizations-v4.0/dataset.pdf
  submissions/2025-04-14-OpenFF-Additional-ChEMBL-Fragment-Optimizations-v4.0/full-env.yaml
  submissions/2025-04-14-OpenFF-Additional-ChEMBL-Fragment-Optimizations-v4.0/generate-dataset.ipynb
  submissions/2025-04-14-OpenFF-Additional-ChEMBL-Fragment-Optimizations-v4.0/input-env.yaml
  submissions/2025-04-14-OpenFF-Additional-ChEMBL-Fragment-Optimizations-v4.0/inputs.tar.gz
  submissions/2025-04-14-OpenFF-Additional-ChEMBL-Fragment-Optimizations-v4.0/output.smi
Labels: tracking, compute-pr454
