Repository openforcefield/qca-dataset-submission, pull requests merged in 2025-03, with the labels that each got.

#431 Add additional optimizations
  README.md
  submissions/2025-03-06-OpenFF-Cresset-Additional-Coverage-Optimizations-v4.0/README.md
  submissions/2025-03-06-OpenFF-Cresset-Additional-Coverage-Optimizations-v4.0/dataset.json.bz2
  submissions/2025-03-06-OpenFF-Cresset-Additional-Coverage-Optimizations-v4.0/dataset.pdf
  submissions/2025-03-06-OpenFF-Cresset-Additional-Coverage-Optimizations-v4.0/full-env.yaml
  submissions/2025-03-06-OpenFF-Cresset-Additional-Coverage-Optimizations-v4.0/generate-dataset.ipynb
  submissions/2025-03-06-OpenFF-Cresset-Additional-Coverage-Optimizations-v4.0/input-env.yaml
  submissions/2025-03-06-OpenFF-Cresset-Additional-Coverage-Optimizations-v4.0/output.smi
Labels: tracking, compute-pr431

#432 Add PDB 4-mers dataset
  .gitattributes
  README.md
  submissions/2025-03-05-OpenFF-Protein-PDB-4mer-v4.0/README.md
  submissions/2025-03-05-OpenFF-Protein-PDB-4mer-v4.0/dataset.json.bz2
  submissions/2025-03-05-OpenFF-Protein-PDB-4mer-v4.0/dataset.pdf
  submissions/2025-03-05-OpenFF-Protein-PDB-4mer-v4.0/dataset.smi
  submissions/2025-03-05-OpenFF-Protein-PDB-4mer-v4.0/generate-dataset.ipynb
  submissions/2025-03-05-OpenFF-Protein-PDB-4mer-v4.0/input-env.yaml
  submissions/2025-03-05-OpenFF-Protein-PDB-4mer-v4.0/inputs.tar.bz2
Labels: tracking, compute_pr432_mw-300

#444 Add cresset hessian dataset
  README.md
  submissions/2025-03-31-OpenFF-Cresset-Additional-Coverage-Hessian-v4.0/README.md
  submissions/2025-03-31-OpenFF-Cresset-Additional-Coverage-Hessian-v4.0/dataset.json.bz2
  submissions/2025-03-31-OpenFF-Cresset-Additional-Coverage-Hessian-v4.0/dataset.pdf
  submissions/2025-03-31-OpenFF-Cresset-Additional-Coverage-Hessian-v4.0/dataset.smi
  submissions/2025-03-31-OpenFF-Cresset-Additional-Coverage-Hessian-v4.0/full-env.yaml
  submissions/2025-03-31-OpenFF-Cresset-Additional-Coverage-Hessian-v4.0/generate-dataset.ipynb
  submissions/2025-03-31-OpenFF-Cresset-Additional-Coverage-Hessian-v4.0/input-env.yaml
Labels: tracking
